// <auto-generated />
using AccessControl.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.DataAccess.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20251001142859_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Model.FeatureKey", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("feature_keys_pkey");

                    b.ToTable("feature_keys", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKeyRole", b =>
                {
                    b.Property<string>("FeatureKeyName")
                        .HasColumnType("text")
                        .HasColumnName("feature_key_name");

                    b.Property<string>("RoleName")
                        .HasColumnType("text")
                        .HasColumnName("role_name");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("permissions");

                    b.HasKey("FeatureKeyName", "RoleName");

                    b.HasIndex("RoleName");

                    b.ToTable("feature_key_role", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Name")
                        .HasName("roles_pkey");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKeyRole", b =>
                {
                    b.HasOne("AccessControl.Model.FeatureKey", "FeatureKey")
                        .WithMany("FeatureKeyAccessRoles")
                        .HasForeignKey("FeatureKeyName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeatureKey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKey", b =>
                {
                    b.Navigation("FeatureKeyAccessRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
