// <auto-generated />
using System;
using AccessControl.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.DataAccess.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20250928061855_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Model.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("access_roles_pkey");

                    b.ToTable("access_roles", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("feature_key_pkey");

                    b.ToTable("feature_key", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKeyRole", b =>
                {
                    b.Property<Guid>("FeatureKeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("FeatureKeyId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("feature_key_role", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKeyRole", b =>
                {
                    b.HasOne("AccessControl.Model.FeatureKey", null)
                        .WithMany("FeatureKeyRoles")
                        .HasForeignKey("FeatureKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Model.AccessRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKey", b =>
                {
                    b.Navigation("FeatureKeyRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
