// <auto-generated />
using System;
using AccessControl.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccessControl.DataAccess.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    partial class AccessControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccessControl.Model.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("access_roles_pkey");

                    b.ToTable("access_roles", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("feature_keys_pkey");

                    b.ToTable("feature_keys", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKeyAccessRole", b =>
                {
                    b.Property<Guid>("AccessRoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("access_role_id");

                    b.Property<Guid>("FeatureKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("feature_key_id");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer")
                        .HasColumnName("permissions");

                    b.HasKey("AccessRoleId", "FeatureKeyId");

                    b.HasIndex("FeatureKeyId");

                    b.ToTable("feature_key_role", (string)null);
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKeyAccessRole", b =>
                {
                    b.HasOne("AccessControl.Model.AccessRole", "AccessRole")
                        .WithMany()
                        .HasForeignKey("AccessRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccessControl.Model.FeatureKey", "FeatureKey")
                        .WithMany("FeatureKeyAccessRoles")
                        .HasForeignKey("FeatureKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessRole");

                    b.Navigation("FeatureKey");
                });

            modelBuilder.Entity("AccessControl.Model.FeatureKey", b =>
                {
                    b.Navigation("FeatureKeyAccessRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
